version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  paytm-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.user
    environment:
      DATABASE_URL: postgres://admin:secret@postgres:5432/mydb
    depends_on:
      - postgres
    ports:
      - "3000:3000"

volumes:
  pgdata:
